language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
sudo: false
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - python setup.py install
script:
  - python setup.py test
  - py.test --cov-config .coveragerc --cov=pyflashtext test/ --doctest-modules -v --cov-report term-missing
after_success:
  - coveralls
