version: '2.0'

    pytest-python3.6:
      image: python:3.6
      command: bash -c "pip install pytest; python setup.py test"
      volumes:
        - .:/app
      working_dir: /app

    pytest-python3.7:
      image: python:3.7
      command: bash -c "pip install pytest; python setup.py test"
      volumes:
        - .:/app
      working_dir: /app

    pytest-python3.8:
      image: python:3.8
      command: bash -c "pip install pytest; python setup.py test"
      volumes:
        - .:/app
      working_dir: /app

    pytest-python3.9:
      image: python:3.9
      command: bash -c "pip install pytest; python setup.py test"
      volumes:
        - .:/app
      working_dir: /app

    pytest-python3.6-i386:
      image: i386/python:3.6
      command: bash -c "pip install pytest; python setup.py test"
      volumes:
        - .:/app
      working_dir: /app

    pytest-python3.7-i386:
      image: i386/python:3.7
      command: bash -c "pip install pytest; python setup.py test"
      volumes:
        - .:/app
      working_dir: /app

    pytest-python3.8-i386:
      image: i386/python:3.8
      command: bash -c "pip install pytest; python setup.py test"
      volumes:
        - .:/app
      working_dir: /app

    pytest-python3.9-i386:
      image: i386/python:3.9
      command: bash -c "pip install pytest; python setup.py test"
      volumes:
        - .:/app
      working_dir: /app
